# Skjema:
# <<tjeneste-id>>: 
#   teamNavn: <<navn på team>>
#   slack: <<kanal hvor vi kan nå dere>>
#   accessPolicy:
#     - <<cluster>>:<<namespace>>:<<app>>
#   merkelapper:
#     - <<merkelapp 1>>
#     - <<merkelapp 2>>
#     - <<..>>
#   mottakere:
#     - serviceCode: <<service code>>
#       serviceEdition: <<service code edition>>
#     - << .... >>
#     - nærmesteLeder
#
# Eksempel:
# 
# innsyn-i-aareg:
#   accessPolicy:
#     - dev-gcp:fager:innsyn-i-aareg-api
#     - prod-gcp:fager:innsyn-i-aareg-api
#   merkelapper:
#     - arbeidsforhold
#   mottakere:
#     - serviceCode: 1234
#       serviceEdition: 1
#     - nærmesteLeder

arbeidsgiver-tiltak:
  teamNavn: Team-tiltak
  slack: "#arbeidsgiver-tiltak"
  bruksvilkårGodkjent: false
  accessPolicy:
    - dev-gcp:arbeidsgiver:tiltak-refusjon-api
    - dev-fss:arbeidsgiver:tiltak-tiltaksgjennomforing-api
  merkelapper:
    - Tiltak
  mottakere:
    - serviceCode: 4936
      serviceEdition: 1
    - serviceCode: 5516
      serviceEdition: 1
    - serviceCode: 5516
      serviceEdition: 2
    - serviceCode: 5516
      serviceEdition: 3
    - serviceCode: 5332
      serviceEdition: 1
