# Skjema:
# <<tjeneste-id>>: 
#   teamNavn: <<navn på team>>
#   slack: <<kanal hvor vi kan nå dere>>
#   accessPolicy:
#     - <<cluster>>:<<namespace>>:<<app>>
#   merkelapper:
#     - <<merkelapp 1>>
#     - <<merkelapp 2>>
#     - <<..>>
#   mottakere:
#     - serviceCode: <<service code>>
#       serviceEdition: <<service code edition>>
#     - << .... >>
#     - nærmesteLeder
#     - altinnReportee
#
# Eksempel:
# 
# innsyn-i-aareg:
#   accessPolicy:
#     - dev-gcp:fager:innsyn-i-aareg-api
#     - prod-gcp:fager:innsyn-i-aareg-api
#   merkelapper:
#     - arbeidsforhold
#   mottakere:
#     - serviceCode: 1234
#       serviceEdition: 1
#     - nærmesteLeder

arbeidsgiver-tiltak:
  teamNavn: Team-tiltak
  slack: "#arbeidsgiver-tiltak"
  bruksvilkårGodkjent: 2021-10-19
  accessPolicy:
    - dev-gcp:arbeidsgiver:tiltak-refusjon-api
    - dev-fss:arbeidsgiver:tiltaksgjennomforing-api
    - prod-fss:arbeidsgiver:tiltaksgjennomforing-api
  merkelapper:
    - Lønnstilskudd
    - Mentor
    - Sommerjobb
    - Arbeidstrening
  mottakere:
    - serviceCode: 4936
      serviceEdition: 1
    - serviceCode: 5516
      serviceEdition: 1
    - serviceCode: 5516
      serviceEdition: 2
    - serviceCode: 5516
      serviceEdition: 3
    - serviceCode: 5332
      serviceEdition: 1

permitteringsmelding-notifikasjon:
  teamNavn: permittering-og-nedbemmaning
  slack: "#permittering-og-nedbemanning-utvikling"
  bruksvilkårGodkjent: 2022-03-23
  accessPolicy:
    - dev-gcp:permittering-og-nedbemanning:permitteringsmelding-notifikasjon
    - prod-gcp:permittering-og-nedbemanning:permitteringsmelding-notifikasjon
  merkelapper:
    - Permittering
    - Nedbemanning
    - Innskrenking av arbeidstid
  mottakere:
    - rolle: DAGL # Daglig leder / adm. direktør (enhetsregisteret)
    - rolle: LEDE # Styrets leder (enhetsregisteret)
    - rolle: REGN # Regnskapsfører

esyfovarsel:
  teamNavn: team-esyfo
  slack: "#esyfo"
  bruksvilkårGodkjent: false
  accessPolicy:
    - dev-gcp:team-esyfo:esyfovarsel
    - dev-fss:team-esyfo:esyfovarsel
    # bruksvilkår enda ikke godkjent
    # - prod-gcp:team-esyfo:esyfovarsel
    # - prod-fss:team-esyfo:esyfovarsel
  merkelapper:
    - Aktivitetskrav
  mottakere:
    - nærmesteLeder

fritakagp:
  teamNavn: helsearbeidsgiver
  slack: "#helse-arbeidsgiver"
  bruksvilkårGodkjent: 2022-04-19
  accessPolicy:
    - dev-gcp:helsearbeidsgiver:fritakagp
  merkelapper:
    - Refusjon
  mottakere:
    - serviceCode: 4936
      serviceEdition: 1
