# Skjema:
# <<tjeneste-id>>:
#   teamNavn: <<navn på team>>
#   slack: <<kanal hvor vi kan nå dere>>
#   accessPolicy:
#     - <<cluster>>:<<namespace>>:<<app>>
#   merkelapper:
#     - <<merkelapp 1>>
#     - <<merkelapp 2>>
#     - <<..>>
#   mottakere:
#     - serviceCode: <<service code>>
#       serviceEdition: <<service code edition>>
#     - << .... >>
#     - nærmesteLeder
#
# Eksempel:
#
# innsyn-i-aareg:
#   accessPolicy:
#     - dev-gcp:fager:innsyn-i-aareg-api
#     - prod-gcp:fager:innsyn-i-aareg-api
#   merkelapper:
#     - arbeidsforhold
#   mottakere:
#     - serviceCode: 1234
#       serviceEdition: 1
#     - nærmesteLeder

arbeidsgiver-tiltak:
  teamNavn: Team-tiltak
  slack: "#arbeidsgiver-tiltak"
  bruksvilkårGodkjent: 2021-10-19
  accessPolicy:
    - dev-fss:arbeidsgiver:tiltaksgjennomforing-api
    - prod-fss:arbeidsgiver:tiltaksgjennomforing-api
    - dev-gcp:team-tiltak:tiltak-notifikasjon
    - prod-gcp:team-tiltak:tiltak-notifikasjon
  merkelapper:
    - Lønnstilskudd
    - Mentor
    - Sommerjobb
    - Arbeidstrening
    - Inkluderingstilskudd
    - Varig tilrettelagt arbeid i ordinær virksomhet
  mottakere:
    - serviceCode: 4936
      serviceEdition: 1
    - serviceCode: 5516
      serviceEdition: 1
    - serviceCode: 5516
      serviceEdition: 2
    - serviceCode: 5516
      serviceEdition: 3
    - serviceCode: 5516
      serviceEdition: 4
    - serviceCode: 5516
      serviceEdition: 5
    - serviceCode: 5516
      serviceEdition: 6
    - serviceCode: 5332
      serviceEdition:
        prod: 2
        other: 1

permitteringsmelding-notifikasjon:
  teamNavn: permittering-og-nedbemmaning
  slack: "#permittering-og-nedbemanning-utvikling"
  bruksvilkårGodkjent: 2022-03-23
  accessPolicy:
    - dev-gcp:permittering-og-nedbemanning:permitteringsmelding-notifikasjon
    - prod-gcp:permittering-og-nedbemanning:permitteringsmelding-notifikasjon
  merkelapper:
    - Permittering
    - Nedbemanning
    - Innskrenking av arbeidstid
  mottakere:
    - serviceCode: 5810
      serviceEdition: 1
    - ressursId: nav_permittering-og-nedbemmaning_innsyn-i-alle-innsendte-meldinger

esyfovarsel:
  teamNavn: team-esyfo
  slack: "#esyfo"
  bruksvilkårGodkjent: true
  accessPolicy:
    - dev-gcp:team-esyfo:esyfovarsel
    - prod-gcp:team-esyfo:esyfovarsel
  merkelapper:
    - Oppfølging
    - Dialogmøte
  mottakere:
    - nærmesteLeder

fritakagp:
  teamNavn: helsearbeidsgiver
  slack: "#helse-arbeidsgiver"
  bruksvilkårGodkjent: 2022-04-19
  accessPolicy:
    - dev-gcp:helsearbeidsgiver:fritakagp
    - prod-gcp:helsearbeidsgiver:fritakagp
  merkelapper:
    - Fritak arbeidsgiverperiode
  mottakere:
    - serviceCode: 4936
      serviceEdition: 1

im-notifikasjon:
  teamNavn: helsearbeidsgiver
  slack: "#helse-arbeidsgiver"
  bruksvilkårGodkjent: 2022-12-05
  accessPolicy:
    - dev-gcp:helsearbeidsgiver:im-notifikasjon
    - prod-gcp:helsearbeidsgiver:im-notifikasjon
    - dev-gcp:helsearbeidsgiver:hag-admin
    - prod-gcp:helsearbeidsgiver:hag-admin
  merkelapper:
    - Inntektsmelding
    - Inntektsmelding sykepenger
  mottakere:
    - serviceCode: 4936
      serviceEdition: 1

toi-arbeidsgiver-notifikasjon:
  teamNavn: toi
  slack: "#arbeidsgiver-toi"
  bruksvilkårGodkjent: 2023-01-27
  accessPolicy:
    - dev-gcp:toi:toi-arbeidsgiver-notifikasjon
    - prod-gcp:toi:toi-arbeidsgiver-notifikasjon
  merkelapper:
    - Kandidater
  mottakere:
    - serviceCode: 5078
      serviceEdition: 1

arbeidsgiver-dialog:
  teamNavn: Team-Dialog
  slack: "#arbeidsgiver-crm"
  bruksvilkårGodkjent: 2023-02-14
  accessPolicy:
    - dev-gcp:teamcrm:saas-proxy
    - dev-external:teamcrm:salesforce
    - prod-gcp:teamcrm:saas-proxy
    - prod-external:teamcrm:salesforce
  merkelapper:
    - Lønnstilskudd
    - Arbeidstrening
  mottakere:
    - serviceCode: 5516
      serviceEdition: 1
    - serviceCode: 5332
      serviceEdition:
        prod: 2
        other: 1

yrkesskade-notifikasjon:
  teamNavn: Team-Yrkesskade
  slack: "#team-yrkesskade"
  bruksvilkårGodkjent: 2024-04-09
  accessPolicy:
    - dev-gcp:yrkesskade:yrkesskade-melding-mottak
    - prod-gcp:yrkesskade:yrkesskade-melding-mottak
    - dev-gcp:yrkesskade:yrkesskade-saksbehandling-backend
    - prod-gcp:yrkesskade:yrkesskade-saksbehandling-backend
  merkelapper:
    - Skademelding
  mottakere:
    - serviceCode: 5902
      serviceEdition: 1

fp-inntektsmelding-notifikasjon:
  teamNavn: Team Foreldrepenger
  slack: "#teamforeldrepenger"
  bruksvilkårGodkjent: 2024-10-02
  accessPolicy:
    - dev-gcp:teamforeldrepenger:fpinntektsmelding
    - prod-gcp:teamforeldrepenger:fpinntektsmelding
  merkelapper:
    - Inntektsmelding foreldrepenger
    - Inntektsmelding svangerskapspenger
  mottakere:
    - serviceCode: 4936
      serviceEdition: 1

k9-inntektsmelding-notifikasjon:
  teamNavn: Sykdom i familien
  slack: "#sykdom-i-familien"
  bruksvilkårGodkjent: 2025-01-29
  accessPolicy:
    - dev-gcp:k9saksbehandling:k9-inntektsmelding
    - prod-gcp:k9saksbehandling:k9-inntektsmelding
  merkelapper:
    - Inntektsmelding omsorgspenger
    - Inntektsmelding pleiepenger sykt barn
    - Inntektsmelding pleiepenger i livets sluttfase
    - Inntektsmelding opplæringspenger
    - Refusjonskrav for omsorgspenger
  mottakere:
    - serviceCode: 4936
      serviceEdition: 1
